Minibuilder
sandia-minimega/minimega pull request #1429
Opened 2020-09-10 00:35 UTC by aherna

2020-10-08 16:57 UTC, csymonds requested changes
Please add copyright as needed

2020-10-08 16:57 UTC, csymonds commented on misc/web/grapheditor/index.html
> +<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=5,IE=9" ><![endif]-->
Sandia copyright statement

2021-01-04 17:51 UTC, aherna commented on misc/web/grapheditor/index.html
> +<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=5,IE=9" ><![endif]-->
Done @csymonds

2021-01-08 00:14 UTC, csymonds approved these changes
LGTM

2021-01-08 00:15 UTC, merged