Refactor minimega code base to use Go Modules
sandia-minimega/minimega pull request #1464
Opened 2022-02-28 18:07 UTC by activeshadow

This PR replaces #1427.

2022-03-18 21:55 UTC, aherna requested changes

2022-05-05 17:54 UTC, activeshadow commented
@aherna any movement on this? Would be great to get this merged!

2022-05-05 19:12 UTC, aherna commented
> @aherna any movement on this? Would be great to get this merged!

Were the issues resolved? Ie all.bash throwing out errors when vetting

2022-05-05 19:17 UTC, activeshadow commented
> > @aherna any movement on this? Would be great to get this merged!
> 
> @activeshadow Were the issues resolved? Ie all.bash throwing out errors when vetting

@aherna I just ran the `all.bash` script and everything worked fine. I'm using Go version 1.17. What version are you testing with? It may be that I need to leave both versions of build directives in the code to support older versions of Go.

2022-05-17 23:19 UTC, activeshadow commented
@aherna okay I've fixed the issue you found (was due to older versions of Go not knowing about the new `go:build` directive). Let's get this merged in shall we?! :+1::joy:

2022-05-17 23:20 UTC, activeshadow commented on cmd/miniccc/process_windows.go
This has been addressed.

2022-06-10 21:29 UTC, activeshadow commented
@aherna anything new with this?

2022-06-15 21:39 UTC, activeshadow commented
@aherna FYSA, I've been running this branch locally and for some other customers and all is working as expected.

2022-07-19 02:01 UTC, activeshadow commented
@aherna can we go ahead and get this merged by chance? I'd like to use it as the basis for the fixes and updates we're currently working on.

2022-07-21 16:36 UTC, aherna approved these changes
LGTM

2022-07-21 16:38 UTC, merged