feat: allow disk inject to delete files
sandia-minimega/minimega pull request #1548
Opened 2024-11-22 12:25 UTC by glattercj

Adds the ability to delete files while doing disk inject via a keyword as the src. E.g.:

`disk inject window7_miniccc.qc2 files "-DELETE-":"Program Files/miniccc.exe"`

2025-01-03 21:33 UTC, jacdavi approved these changes
Tested and looks good. Two UX considerations though:

* Would it make sense to have the syntax be `disk inject <image> delete files <files like /path/to/dst>`? I realize it would require a bit more refactoring, but on the surface it seems more intuitive to me
* Would it be useful to log a warning if a file the user tries to delete doesn't exist? I fat-fingered a path in testing, and wouldn't have noticed if I wasn't manually verifying the image after. `os.RemoveAll` just returns `nil` in that case, so we'd have to separately check if the file exists.

2025-01-20 22:22 UTC, glattercj commented
@jacdavi 

- Updated to use your suggested format. E.g.:

    ```bash
    disk inject window7_miniccc.qc2 delete files "Program Files/miniccc.exe"
    ```

- Added warning if path doesn't exist for deletion

2025-01-28 00:51 UTC, jacdavi commented
Thanks I think those are both really good changes! It does seem like there's an issue parsing when deleting a single file. Based on the docstring I think this should work?

```
minimega[minimega]$ disk inject /scratch/images/test.qcow2 delete files /etc/setup.sh
Error (ccc19.40g): malformed command; expected src:dst pairs
```

2025-01-29 01:33 UTC, glattercj commented
> Thanks I think those are both really good changes! It does seem like there's an issue parsing when deleting a single file. Based on the docstring I think this should work?
> 
> ```
> minimega[minimega]$ disk inject /scratch/images/test.qcow2 delete files /etc/setup.sh
> Error (ccc19.40g): malformed command; expected src:dst pairs
> ```

@jacdavi Good catch, I missed the single file case 🤦 . Updated and tested.

2025-01-29 02:39 UTC, jacdavi requested changes
Sorry for so much back and forth. Two final things and then it should be all set!

2025-01-29 02:39 UTC, jacdavi commented on cmd/minimega/disk.go
> +		if strings.Contains(v, ",") {
Can the single case also be added here. Otherwise it doesn' t work with options specified

```
minimega[minimega]$ disk inject /scratch/images/test.qcow2 options "-o offset=0" delete files /bin/foo
Error (ccc19.40g): malformed command; expected src:dst pairs
```

2025-01-29 02:39 UTC, jacdavi commented on cmd/minimega/disk.go
> +		if len(options) == 0 {
I accidentally found a panic here if you use `disk inject image.qcow2 options "" files /bin/foo` as this if evaluates to true, but the parser has made `files` a string. 

Fix should just be `if _, ok := c.StringArgs["options"]; !ok {` so we just check whether the user specified options

2025-01-29 04:53 UTC, glattercj commented on cmd/minimega/disk.go
> +		if strings.Contains(v, ",") {
Fixed

2025-01-29 05:01 UTC, glattercj commented on cmd/minimega/disk.go
> +		if len(options) == 0 {
I'm not able to repro this. I changed the `if` check to match your fix but here's what I'm getting both before and after making the change:

```bash
$ disk inject image.qcow2 options "" files /bin/foo
Error (crn1): invalid command: `disk inject image.qcow2 options  files /bin/foo`
```

If I add the `delete` keyword it just returns without any output. Looking at some debug output the minicli.Command just turns the empty quotes into a blank so `c.StringArgs["options"]` returns the next token being `delete`.

```bash
$ disk inject image.qcow2 options "" delete files /bin/foo

```

2025-01-29 18:29 UTC, jacdavi commented on cmd/minimega/disk.go
> +		if len(options) == 0 {
Hmm it was happening to me every time. Regardless it looks good now

```
minimega[minimega]$ disk inject /scratch/images/test.qcow2 options "" files /bin/foo
panic: runtime error: index out of range [0] with length 0

goroutine 99 [running]:
main.parseFiles({0x8d0cc0?, 0xc0000a4df0?})
        /scratch/minimega/cmd/minimega/disk.go:370 +0x276
main.cliDisk(0x0?, 0xc0000c2780, 0xc00053e400)
        /scratch/minimega/cmd/minimega/disk.go:442 +0x5eb
main.wrapSimpleCLI.func1(0xc0000c2780?, 0xc0001129c0?)
        /scratch/minimega/cmd/minimega/cli.go:104 +0x8b
github.com/sandia-minimega/minimega/v2/pkg/minicli.ProcessCommand.func1()
        /scratch/minimega/pkg/minicli/minicli.go:173 +0x196
created by github.com/sandia-minimega/minimega/v2/pkg/minicli.ProcessCommand
        /scratch/minimega/pkg/minicli/minicli.go:160 +0xca
```

2025-01-29 18:32 UTC, jacdavi requested changes

2025-01-29 18:32 UTC, jacdavi commented on cmd/minimega/disk.go
> +		if !(sliceContainsCharacters(v, ",:")) {
Final final thing I promise :) 

With this change we no longer get the error "malformed command; expected src:dst pairs" when running `disk inject /scratch/images/test.qcow2 files /bin/foo`.

Maybe the code should just be explicit whether it expects single files or pairs based on the delete flag?

2025-02-03 20:59 UTC, glattercj commented on cmd/minimega/disk.go
> +		if !(sliceContainsCharacters(v, ",:")) {
@jacdavi I changed the logic a bit to handle this case and tried all the previous ones you had asked about. I think it covers them all. Let me know what you think.

2025-02-17 15:25 UTC, glattercj commented on cmd/minimega/disk.go
> +		if !(sliceContainsCharacters(v, ",:")) {
@jacdavi bump

2025-02-18 01:26 UTC, jacdavi commented on cmd/minimega/disk.go
> +		if !(sliceContainsCharacters(v, ",:")) {
Thanks for the reminder, looks good now!

2025-02-18 01:26 UTC, jacdavi approved these changes

2025-02-18 01:26 UTC, merged